// <auto-generated />
// Generated by Flattiverse.Gateway.TypeGen. Do not edit manually.

export type ChatScope = 'galaxy' | 'team' | 'private';

export type CommandStatus = 'accepted' | 'completed' | 'rejected';

export type GatewayMessageDirection = 'client' | 'server';

export type ServerStatusKind = 'info' | 'warning' | 'error';

export type ShipClass = 'classic' | 'modern';

export interface AttachConnectionMessage {
  type: 'connection.attach';
  payload: AttachConnectionPayloadDto;
}

export interface AttachConnectionPayloadDto {
  apiKey: string;
  teamName?: string;
}

export interface ChatCommandMessage {
  type: 'command.chat';
  commandId: string;
  payload: ChatCommandPayloadDto;
}

export interface ChatCommandPayloadDto {
  scope: ChatScope;
  message: string;
  recipientPlayerSessionId?: string;
}

export interface ChatEntryDto {
  messageId: string;
  scope: ChatScope;
  senderDisplayName: string;
  playerSessionId?: string;
  message: string;
  sentAtUtc: string;
}

export interface ChatReceivedMessage {
  type: 'chat.received';
  entry: ChatEntryDto;
}

export interface ClearNavigationTargetCommandMessage {
  type: 'command.clear_navigation_target';
  commandId: string;
  payload: ClearNavigationTargetCommandPayloadDto;
}

export interface ClearNavigationTargetCommandPayloadDto {
  controllableId: string;
}

export interface ClusterSnapshotDto {
  id: number;
  name: string;
  isStart: boolean;
  respawns: boolean;
}

export interface CommandReplyMessage {
  type: 'command.reply';
  commandId: string;
  status: CommandStatus;
  result?: Record<string, unknown>;
  error?: ErrorInfoDto;
}

export interface ContinueShipCommandMessage {
  type: 'command.continue_ship';
  commandId: string;
  payload: ContinueShipCommandPayloadDto;
}

export interface ContinueShipCommandPayloadDto {
  controllableId: string;
}

export interface CreateShipCommandMessage {
  type: 'command.create_ship';
  commandId: string;
  payload: CreateShipCommandPayloadDto;
}

export interface CreateShipCommandPayloadDto {
  shipClass: ShipClass;
  name: string;
  crystalNames: string[];
}

export interface DestroyShipCommandMessage {
  type: 'command.destroy_ship';
  commandId: string;
  payload: DestroyShipCommandPayloadDto;
}

export interface DestroyShipCommandPayloadDto {
  controllableId: string;
}

export interface DetachPlayerSessionMessage {
  type: 'connection.detach';
  playerSessionId: string;
}

export interface ErrorInfoDto {
  code: string;
  message: string;
  recoverable: boolean;
}

export interface FireWeaponCommandMessage {
  type: 'command.fire_weapon';
  commandId: string;
  payload: FireWeaponCommandPayloadDto;
}

export interface FireWeaponCommandPayloadDto {
  controllableId: string;
  weaponId: string;
  relativeAngle?: number | null;
  targetId?: string;
}

export interface GalaxySnapshotDto {
  name: string;
  description: string;
  gameMode?: string;
  teams: TeamSnapshotDto[];
  clusters: ClusterSnapshotDto[];
  units: UnitSnapshotDto[];
  controllables: PublicControllableSnapshotDto[];
}

export interface OwnerOverlayDeltaDto {
  eventType: string;
  controllableId: string;
  changes?: Record<string, unknown>;
}

export interface OwnerOverlayDeltaMessage {
  type: 'owner.delta';
  playerSessionId: string;
  events: OwnerOverlayDeltaDto[];
}

export interface PingMessage {
  type: 'ping';
}

export interface PlayerSessionSummaryDto {
  playerSessionId: string;
  displayName: string;
  connected: boolean;
  selected: boolean;
  teamName?: string;
}

export interface PongMessage {
  type: 'pong';
}

export interface PublicControllableSnapshotDto {
  controllableId: string;
  displayName: string;
  teamName: string;
  alive: boolean;
  score: number;
}

export interface RemoveShipCommandMessage {
  type: 'command.remove_ship';
  commandId: string;
  payload: RemoveShipCommandPayloadDto;
}

export interface RemoveShipCommandPayloadDto {
  controllableId: string;
}

export interface SelectPlayerSessionMessage {
  type: 'player.select';
  playerSessionId: string;
}

export interface ServerStatusMessage {
  type: 'status';
  kind: ServerStatusKind;
  code: string;
  message: string;
  recoverable: boolean;
}

export interface SessionReadyMessage {
  type: 'session.ready';
  connectionId: string;
  protocolVersion: string;
  observerOnly: boolean;
  playerSessions: PlayerSessionSummaryDto[];
}

export interface SetEngineCommandMessage {
  type: 'command.set_engine';
  commandId: string;
  payload: SetEngineCommandPayloadDto;
}

export interface SetEngineCommandPayloadDto {
  controllableId: string;
  engineId: string;
  thrust?: number | null;
  x?: number | null;
  y?: number | null;
}

export interface ScannerCommandMessage {
  type: 'command.scanner';
  commandId: string;
  payload: ScannerCommandPayloadDto;
}

export interface ScannerCommandPayloadDto {
  controllableId: string;
  mode?: string | null;
  width?: number | null;
}

export interface SetNavigationTargetCommandMessage {
  type: 'command.set_navigation_target';
  commandId: string;
  payload: SetNavigationTargetCommandPayloadDto;
}

export interface SetNavigationTargetCommandPayloadDto {
  controllableId: string;
  targetX: number;
  targetY: number;
  thrustPercentage?: number | null;
}

export interface SetSubsystemModeCommandMessage {
  type: 'command.set_subsystem_mode';
  commandId: string;
  payload: SetSubsystemModeCommandPayloadDto;
}

export interface SetSubsystemModeCommandPayloadDto {
  controllableId: string;
  subsystemId: string;
  mode: string;
  value?: number | null;
  targetId?: string;
}

export interface SnapshotMessage {
  type: 'snapshot.full';
  snapshot: GalaxySnapshotDto;
}

export interface TeamSnapshotDto {
  id: number;
  name: string;
  score: number;
  colorHex: string;
}

export interface UnitSnapshotDto {
  unitId: string;
  clusterId: number;
  kind: string;
  isStatic: boolean;
  isSeen: boolean;
  lastSeenTick: number;
  x: number;
  y: number;
  angle: number;
  radius: number;
  teamName?: string;
  sunEnergy?: number | null;
  sunIons?: number | null;
  sunNeutrinos?: number | null;
  sunHeat?: number | null;
  sunDrain?: number | null;
}

export interface WorldDeltaDto {
  eventType: string;
  entityId: string;
  changes?: Record<string, unknown>;
}

export interface WorldDeltaMessage {
  type: 'world.delta';
  events: WorldDeltaDto[];
}

export type ServerMessage = ChatReceivedMessage | CommandReplyMessage | OwnerOverlayDeltaMessage | PingMessage | ServerStatusMessage | SessionReadyMessage | SnapshotMessage | WorldDeltaMessage;

export type ClientMessage = AttachConnectionMessage | ChatCommandMessage | ClearNavigationTargetCommandMessage | ContinueShipCommandMessage | CreateShipCommandMessage | DestroyShipCommandMessage | DetachPlayerSessionMessage | FireWeaponCommandMessage | PongMessage | RemoveShipCommandMessage | ScannerCommandMessage | SelectPlayerSessionMessage | SetEngineCommandMessage | SetNavigationTargetCommandMessage | SetSubsystemModeCommandMessage;
